name: dev-build
"on":
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Add SHORT_SHA env property
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Add TAG_NAME env property
        run: echo "TAG_NAME=`echo ${GITHUB_REF#refs/tags/}`" >> $GITHUB_ENV
      - name: Display the path
        run: echo $PATH
        shell: bash
      - name: Build the Docker image
        run: docker build --tag img:${GITHUB_RUN_ID} --build-arg TAG_NAME=${TAG_NAME} --build-arg SHORT_SHA=${SHORT_SHA} --file Dockerfile .
      # - name: GCR Image Push
      #   run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Run
        run: docker run img:${GITHUB_RUN_ID}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "img:${GITHUB_RUN_ID}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
